# configuration spec can be found here https://release-plz.ieni.dev/docs/config

[workspace]
pr_draft = true
dependencies_update = true
changelog_config = "cliff.toml"

[changelog]
protect_breaking_commits = true
